#  Codecov Configuration - Sistema GYS
# 
# Configuraci贸n para an谩lisis de cobertura de c贸digo
# con thresholds espec铆ficos y reportes detallados.
# 
# @author TRAE - Agente Senior Fullstack
# @version 1.0.0

coverage:
  #  Configuraci贸n de precisi贸n
  precision: 2
  round: down
  range: "70...100"
  
  #  Configuraci贸n de status checks
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
        flags:
          - unittests
        paths:
          - "src/"
    
    patch:
      default:
        target: 80%
        threshold: 1%
        base: auto
        flags:
          - unittests
    
    changes:
      default:
        target: 80%
        threshold: 1%
        base: auto
        flags:
          - unittests

#  Configuraci贸n de flags
flags:
  unittests:
    paths:
      - src/
    carryforward: false
  
  integration:
    paths:
      - src/
    carryforward: false
  
  e2e:
    paths:
      - e2e/
    carryforward: false

#  Configuraci贸n de comentarios en PR
comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  branches:
    - main
    - develop

#  Archivos a ignorar
ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/__tests__/**"
  - "**/__mocks__/**"
  - "**/e2e/**"
  - "**/coverage/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/.next/**"
  - "**/node_modules/**"
  - "**/*.config.js"
  - "**/*.config.ts"
  - "**/tailwind.config.js"
  - "**/next.config.js"
  - "**/playwright.config.ts"
  - "**/vitest.config.ts"
  - "**/jest.config.js"
  - "**/.eslintrc.js"
  - "**/prettier.config.js"
  - "**/postcss.config.js"
  - "**/middleware.ts"
  - "**/instrumentation.ts"
  - "src/app/globals.css"
  - "src/app/layout.tsx"
  - "src/app/loading.tsx"
  - "src/app/error.tsx"
  - "src/app/not-found.tsx"
  - "prisma/**"
  - "public/**"
  - "docs/**"
  - "*.md"
  - "*.mdx"

#  Configuraci贸n de parsers
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

#  Configuraci贸n de GitHub Checks
github_checks:
  annotations: true

#  Configuraci贸n de Slack (opcional)
# slack:
#   url: "secret:SLACK_WEBHOOK_URL"
#   threshold: 1%
#   message: |
#     Coverage for {{ owner }}/{{ repo }} changed by {{ range }}% ({{ commit }})
#     {{ author }} - {{ message }}

#  Configuraci贸n avanzada
validation:
  # Validar que el archivo de cobertura existe
  require_ci_to_pass: yes
  
  # Validar cambios m铆nimos
  notify:
    after_n_builds: 1
    countdown: 1
    delay: 0

#  Configuraci贸n de archivos de cobertura
coverage_files:
  - "coverage/lcov.info"
  - "coverage/coverage-final.json"
  - "coverage/clover.xml"

#  Configuraci贸n de notificaciones
notifications:
  email:
    layout: "condensed_header,condensed_files,condensed_footer"
    require_ci_to_pass: yes
    flags:
      - unittests
  
  webhook:
    # url: "secret:WEBHOOK_URL"
    threshold: 1%

#  Configuraci贸n de profiling
profiling:
  critical_files_paths:
    - "src/lib/services/**"
    - "src/app/api/**"
    - "src/components/**"
  
  precision: 2

#  Configuraci贸n de archivos cr铆ticos
critical_files:
  paths:
    - "src/lib/auth.ts"
    - "src/lib/prisma.ts"
    - "src/lib/services/**"
    - "src/app/api/**"
    - "src/middleware.ts"
  
  threshold: 90%