export { BloqueIdentificacion } from './BloqueIdentificacion'
export { BloqueAlcance } from './BloqueAlcance'
export { BloqueSuministros } from './BloqueSuministros'
export { BloquePersonal } from './BloquePersonal'
export { BloquePlazos } from './BloquePlazos'
export { BloqueSsoma } from './BloqueSsoma'
export { BloqueComercial } from './BloqueComercial'
export { BloqueEntregables } from './BloqueEntregables'

export type { BloqueIdentificacionDatos } from './BloqueIdentificacion'
export type { BloqueAlcanceDatos } from './BloqueAlcance'
export type { BloqueSuministrosDatos } from './BloqueSuministros'
export type { BloquePersonalDatos } from './BloquePersonal'
export type { BloquePlazOsDatos as BloquePlazostDatos } from './BloquePlazos'
export type { BloqueSsomaDatos } from './BloqueSsoma'
export type { BloqueComercialDatos } from './BloqueComercial'
export type { BloqueEntregablesDatos } from './BloqueEntregables'
